### ISSUE TITLE
Solution scope of Yuck?

### ISSUE THREAD

**Issue by a1880** [informarte/yuck#12]
The attached MiniZinc example is solved by most non-local solvers in less than 10 seconds.
Local search solvers like Yuck or OSCAR-CLBS are unable to find such a quick solution.

Is there a general explanation for this?
Which problems are suitable for local search?

Greetings,

Axel Kemper

```
%
%  MiniZinc problem
%
%  Solve system of Brent's equations modulo 2
%
%  Axel Kemper  17-Dec-2013  1st experiments

%  Matrix dimensions
int: aRows = 2;
int: aCols = 2;
int: bCols = 2;
int: noOfProducts = 7;

%  Dependent parameters
int: bRows = aCols;
int: cRows = aRows;
int: cCols = bCols;

int: noOfOddEquations = aRows*aCols*bCols;
int: noOfProducts2 = noOfOddEquations - noOfProducts;

set of int: ARows = 1..aRows;
set of int: ACols = 1..aCols;
set of int: BRows = 1..bRows;
set of int: BCols = 1..bCols;
set of int: CRows = 1..cRows;
set of int: CCols = 1..cCols;
set of int: Products = 1..noOfProducts;

int: maxNoOfProducts = 27;
array[1..maxNoOfProducts] of string: 
    productName = 
	["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", 
     "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", 
     "u", "v", "w", "x", "y", "z", "A"];

%  Corefficients are stored in arrays
array[ARows, ACols, Products] of var bool: F;
array[BRows, BCols, Products] of var bool: G;
array[CRows, CCols, Products] of var bool: D;

%  every odd equation has exactly one non-zero triple
constraint
  forall(i in ARows, j in ACols, n in BCols)(
    xorall([ F[i,j,k] /\ G[j,n,k] /\ D[i,n,k] | k in Products])
  );

%  constraint for even equations
constraint
  forall(i in ARows, j in ACols, 
         m in BRows, n in BCols, 
         p in CRows, q in CCols 
         where not delta(i,j,m,n,p,q)) (
    iffall([ F[i,j,k] /\ G[m,n,k] /\ D[p,q,k] | k in Products])
  );
             
% delta false = even, true = odd
function bool: delta(int: i, int: j, int: m, int: n, int: p, int: q) =
  ((i == p) /\ (j == m) /\ (n == q));


```

**Comment by informarte** [comment]
Your model does not have a search strategy, so solvers use their default strategies, leading to very different runtimes. On my laptop, I obtained the following numbers:

- Gecode: 0.15s
- OR-Tools: 5.2s
- Chuffed: 77s

That's why MiniZinc models usually come with a search strategy. However, MiniZinc only has support for tree search, there is no way to define a neighbourhood for local search, giving tree search a competitive edge over local search.

There was an attempt to extend MiniZinc with a DSL for defining neighbourhoods for local search (see [Declarative Local-Search Neighbourhoods in MiniZinc](https://www.it.uu.se/research/group/optimisation/publications/ICTAI18.pdf)) but the extension unfortunately never made it to the MiniZinc mainline.

Running minizinc with the `-v` option reveals that Yuck nearly solves your problem but ultimately fails to resolve a last constraint violation. The minizinc-benchmarks library has a couple of problems where Yuck exhibits such behaviour but I have so far made no serious attempt to understand it. My intuition is that these are problems where, like in a puzzle, many pieces have to fall into the exact right place, which may be hard to achieve with a generic, automatically generated neighbourhood. 

Over the years, local search was applied successfully in many application areas, for example:

- Vehicle routing
- Employee rostering
- Conference scheduling
- School timetabling
- Job-shop scheduling

I compiled the above list from the following sources:

- E. Aarts and J. K. Lenstra. _Local Search in Combinatorial Optimization_. Princeton University Press, 2003.
- P. V. Hentenryck and L. Michel. _Constraint-Based Local Search_. MIT Press, 2005.
- https://www.optaplanner.org/
- https://developers.google.com/optimization/routing

Also the MiniZinc challenge results can point to promising application areas for local search. However, the numbers must be taken with a grain of salt:

- The models were often crafted with a particular solver (technology) in mind and might not be suited for local search, see my report [Extending Yuck for Vehicle Routing](https://github.com/informarte/yuck/releases/download/20210501/Extending_Yuck_for_Vehicle_Routing.pdf), for example.
- As mentioned before, the models do not provide neighbourhoods for local search, so the results only apply to local search with generic neighbourhoods. 
- Both Yuck and Oscar/CBLS have improved over time and now perform better than they did in the early challenges.

Finally I want to mention a feature that sets Yuck apart from the other MiniZinc backends: support for soft constraints in terms of the [goal_hierarchy](https://github.com/informarte/yuck#goal-hierarchies) annotation. So if you want to use MiniZinc, Yuck reliably solves your hard constraints, and you need to consider a hierarchy of optimization goals, then Yuck is your solver.

**Comment by a1880** [comment]
Wow! Thank you very much for this elaborate answer.
