### ISSUE TITLE
Yuck 20230623 - Homebrew compilation issue 

### ISSUE THREAD

**Issue by Dekker1** [informarte/yuck#15]
Updating the MiniZinc Homebrew tap with the new version of Yuck, I'm running into an compilation error: https://github.com/Dekker1/homebrew-minizinc/actions/runs/5384051156/jobs/9771520277?pr=42#step:8:97

I'm running `mill yuck.dev.universalPackage`, but it seems to be running into an issue with the version of `mill` being different from the version stated in the directory. I would prefer to stay with the version of `mill` provided in the Homebrew infrastructure, but you might know better whether this is possible.

**Comment by informarte** [comment]
Try running './mill' instead of 'mill'.

**Comment by Dekker1** [comment]
I thought it would be better to use the Homebrew version, since there is no addition download (if it is already on your system), and no left-overs on the system. However, since this is at least working. I will change the system to use the `mill` script instead.

**Comment by informarte** [comment]
Homebrew's mill version is incompatible with Yuck's build script: 0.11.0 introduced breaking changes. Upgrading Yuck's build script is on my backlog but it has no priority.

Using the `./mill` bootstrap script is not a work-around, it is the recommended way of using mill, see http://mill-build.com/mill/Installation_IDE_Support.html, to avoid all sorts of problems at the price of installing mill into the user's home directory.

Btw, I suggest to build the `yuck.dev.corePackage` target instead of `yuck.dev.universalPackage` as your formula uses only the artifacts from the former.

**Comment by Dekker1** [comment]
Thanks for the pointers, I'll update the package accordingly
